[spacing]
# MARGIN creates dead space with no input tracking
MARGIN_TOP = 30 
MARGIN_RIGHT = 30
PADDING_Y = 20
PADDING_X = 20

# when you click on an applet, expanded menu shows up
EXPANDED_WIDTH = 400
EXPANDED_HEIGHT = 300
EXPANDED_ROUNDING = 50

# DEFORM_PADDING is like margin, but keeps the input area and can be partly intruded by the animation deformations, depending on WEIGHT in [deform properties]
DEFORM_PADDING = 10 

# extra space for the input area in case you want to expand it. def = 5
INPUT_EXTRA = 5

[deform properties]
# 1=linear, 2=quadratic, 3=cubic falloff def = 2.0
FALLOFF = 3.0 

# range from 1 to 0. Rounding quality
QUALITY = 1.0 

# range from 1 to 0. Weight decided how far animation deformations can intrude the deform_padding.
WEIGHT = 0.8 

# how far cursor affects edge (pixels)
INFLUENCE = 80 

# if not set - quality dictates samples. try SAMPLES = 3, 4 or dont use it
# SAMPLES = <int> 

# like weight but in pixels
# STRENGTH = <int>

[style]
BACKGROUND_COLOR = #ffffff
COLOR = #000
ARROW_COLOR = #000
ARROW_HOVER_OPACITY = 0.3
APPLET_BACKGROUND = transparent
APPLET_BACKGROUND_HOVER = #2222221a

# highlights island's input catching area
PILL_BORDER_WIDTH = 0
PILL_BORDER_COLOR = #222

# highlights pill's input catching area
APPLETS_BORDER_WIDTH = 0
APPLETS_BORDER_COLOR = #2222221e